@startuml
namespace dto {
    class Activity << (S,Aquamarine) >> {
        + ID string
        + UserID string
        + UserName string
        + OldPatient *Patient
        + NewPatient *Patient
        + OldSwab *Swab
        + NewSwab *Swab
        + Time int64
        + TTL time.Time

    }
    class AuthObject << (S,Aquamarine) >> {
        + Token string
        + UserId string
        + DisplayName string
        + TTL time.Time
        + Type string

    }
    class CallingReport << (S,Aquamarine) >> {
        + Date string
        + DontHaveToCall int64
        + PatientCalled int64
        + UMMCCalled int64
        + NoYetCall int64
        + PuiDontHaveToCall int64
        + PuiPatientCalled int64
        + PuiUMMCCalled int64
        + PuiNoYetCall int64
        + ContactDontHaveToCall int64
        + ContactPatientCalled int64
        + ContactUMMCCalled int64
        + ContactNoYetCall int64

    }
    class Declaration << (S,Aquamarine) >> {
        + ID string
        + PatientID string
        + PatientName string
        + PatientType int64
        + Cough int64
        + Throat int64
        + Fever int64
        + Breathe int64
        + Chest int64
        + Blue int64
        + Drowsy int64
        + HasSymptom bool
        + SubmittedAt int64
        + CallingStatus int64
        + Date string
        + PatientPhoneNumber string
        + DoctorRemarks string
        + Loss int64

    }
    class DeclarationReport << (S,Aquamarine) >> {
        + Date string
        + UndeclaredCount int64
        + DeclaredCount int64
        + PuiUndeclaredCount int64
        + PuiDeclaredCount int64
        + ContactUndeclaredCount int64
        + ContactDeclaredCount int64

    }
    class FilterData << (S,Aquamarine) >> {
        + Item string
        + Value string

    }
    class Message << (S,Aquamarine) >> {
        + ChatID string
        + Text string
        + ReplyMarkup *ReplyMarkup

    }
    class Patient << (S,Aquamarine) >> {
        + ID string
        + Name string
        + TelegramID string
        + PhoneNumber string
        + Email string
        + Status int64
        + LastDeclared int64
        + SwabCount int64
        + Episode int64
        + Type int64
        + TypeChangeDate string
        + LastDeclareResult bool
        + ExposureDate string
        + ExposureSource string
        + DaysSinceExposure int64
        + RegistrationNum string
        + AlternateContact string
        + IsolationAddress string
        + SymptomDate string
        + SwabDate string
        + FeverContDay int64
        + Remarks string
        + Localization int64
        + Consent int64
        + PrivacyPolicy int64
        + CallingStatus int64
        + FeverStartDate string
        + DaysSinceSwab int64
        + HomeAddress string
        + IsSameAddress bool

    }
    class PatientStatusReport << (S,Aquamarine) >> {
        + Date string
        + Symptomatic int64
        + Asymptomatic int64
        + ConfirmedButNotAdmitted int64
        + ConfirmedAndAdmitted int64
        + Completed int64
        + Quit int64
        + Recovered int64
        + PassedAway int64
        + PuiSymptomatic int64
        + PuiAsymptomatic int64
        + PuiConfirmedButNotAdmitted int64
        + PuiConfirmedAndAdmitted int64
        + PuiCompleted int64
        + PuiQuit int64
        + PuiRecovered int64
        + PuiPassedAway int64
        + ContactSymptomatic int64
        + ContactAsymptomatic int64
        + ContactConfirmedButNotAdmitted int64
        + ContactConfirmedAndAdmitted int64
        + ContactCompleted int64
        + ContactQuit int64
        + ContactRecovered int64
        + ContactPassedAway int64

    }
    class RangeData << (S,Aquamarine) >> {
        + From int
        + To int

    }
    class ReplyMarkup << (S,Aquamarine) >> {
        + RemoveKeyboard bool

    }
    class SortData << (S,Aquamarine) >> {
        + Item string
        + Order string

    }
    class Swab << (S,Aquamarine) >> {
        + ID string
        + PatientID string
        + PatientName string
        + PatientPhoneNumber string
        + PatientType int64
        + Status int64
        + Date string
        + Location string
        + IsOtherSwabLocation bool

    }
    class User << (S,Aquamarine) >> {
        + ID string
        + Role string
        + DisplayName string
        + PhoneNumber string
        + Email string
        + Password string
        + Disabled bool
        + AccessToken string
        + RefreshToken string
        + ResetToken string
        + AccessUuid string
        + RefreshUuid string
        + AtExpires int64
        + RtExpires int64
        + ResetExpires int64

    }
}


@enduml
